apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-release-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      webhookUrl:
        secretRef: slack-release-webhook-url
  secrets:
    - name: slack-release-webhook-url
      value: projects/336625802684/secrets/slack-release-webhook-url/versions/latest
